### PR TITLE
Add a DefaultConvert() function for compatibility with client-go v0.17.x

### PR DESCRIPTION
**Pull request by andrewmyhre**
@ChrisRx 
Our components are all using the Kubernetes v0.17.x modules. CABPC is compatible except for this conversion file which implements its own conversion scope. The conversion scope interface changed from v0.17 to v0.18. Adding the missing v0.17 function fixes the backwards compatibility.

Another solution might be to not implement a custom scope and just use the scope variable which is passed in to the conversion function by API machinery. Would this cause breakages?

### CODE REVIEW

**Comment by ChrisRx** [comment]
I had to make that custom scope to prevent the call to `Convert()` here on a `nil` value:
https://github.com/criticalstack/cluster-api-bootstrap-provider-crit/blob/793f4c851ea16804295cbc056662e60282712d07/apis/controlplane/v1alpha1/zz_generated.conversion.go#L159-L162

It keeps generating this line and looking in the controller-gen source there did not appear to have a way to prevent it from doing so.  To use it with the controller-tools conversion stuff, it doesn't appear to have a way from there to construct a `conversion.Scope` so it can only pass a nil.  That didn't seem to be a problem until that particular situation above where that call to `Convert()` couldn't be avoided.  If you have a way to get the `conversion.Scope` that can be provided in places like here:
https://github.com/criticalstack/cluster-api-bootstrap-provider-crit/blob/793f4c851ea16804295cbc056662e60282712d07/apis/controlplane/v1alpha1/critcontrolplane_conversion.go#L29

then that would be cool, otherwise I think just adding the method to the custom scope also works.

**Comment by andrewmyhre** [comment]
Ok, are you happy to approve this PR?

**Comment by ChrisRx** [comment]
> Ok, are you happy to approve this PR?

Do you have a way to get the conversion.Scope that can be provided in places like here: https://github.com/criticalstack/cluster-api-bootstrap-provider-crit/blob/793f4c851ea16804295cbc056662e60282712d07/apis/controlplane/v1alpha1/critcontrolplane_conversion.go#L29

As mentioned above, I made the custom scope because I wasn't able to find a way to provide that `conversion.Scope` in controller-tools conversion functions.  If there is a way to do that I would much rather go that route, otherwise I'd be fine with accepting this PR.

**Comment by andrewmyhre** [comment]
I can look into it, but I have some other things I need to get out of the way first which depend on this change

**Comment by ChrisRx** [comment]
That sounds good, this change is acceptable and we can always circle back to alternatives.  Thanks!

**Review by ChrisRx — APPROVED** [review]
lgtm

**Pull request merged**
